import Link from 'next/link';

export default function ProjectDetail() {
  return (
    <div className="mx-auto max-w-[1400px] px-6">
      <div className="grid grid-cols-1 md:grid-cols-12 gap-x-8">

        {/* ASIDE: 4 columns */}
        <aside className="md:col-span-4 md:border-r border-black/70">
          <div className="md:sticky md:top-10 py-6 md:py-10 space-y-6 md:space-y-8 px-4">

            {/* --- BACK BUTTON --- */}
            <Link
              href="/"
              className="group flex items-center gap-2 font-sans-serif text-xs font-light uppercase tracking-normal text-black no-underline hover:opacity-70 transition-all"
            >
              <span className="transition-transform group-hover:-translate-x-1">←</span>
              Back to Home
            </Link>

            <div>
              <h1 className="text-xl md:text-2xl leading-[1.2] font-sans-serif-2 font-semibold tracking-tight text-black/90">
                Urban Heat Islands. These Are the Hottest Places in Buenos Aires
              </h1>
              <p className="text-[14px] md:text-[14px] text-[#484848] font-sans-serif uppercase">Published at La Nación</p>
            </div>

            <div className="space-y-4">
              <div>
                <h4 className="text-[12px] font-bold leading-[1.3] font-sans-serif uppercase">Role</h4>
                <p className="text-sm font-sans-serif font-light">Web Development</p>
              </div>

              <div>
                <h4 className="text-[12px] font-bold leading-[1.3] font-sans-serif uppercase">Publication Date</h4>
                <p className="text-sm font-sans-serif font-light">01/09/2022</p>
              </div>

              <div>
                <h4 className="text-[12px] font-bold leading-[1.3] font-sans-serif uppercase">Co-Authors</h4>
                <p className="text-sm font-sans-serif font-light">La Nación's Visual, Data and Video Teams</p>
              </div>

              <button className="text-[var(--text-title)] border-3 border-[var(--text-title)] py-2 px-4 hover:bg-[var(--text-title)] hover:text-white transition-all cursor-pointer font-sans-serif font-bold text-[12px] uppercase mt-4">
                View Project
              </button>
            </div>
          </div>
        </aside>

        {/* MAIN: 8 columns */}
        <main className="md:col-span-8 py-6 md:py-10 space-y-8 md:space-y-12">

          {/* Hero image */}
          <div className="overflow-hidden">
            <img
              src="/images/islas/apertura.png"
              alt="Full view"
              className="w-full h-auto object-cover"
            />
          </div>

          <section className="grid grid-cols-4 md:grid-cols-8 gap-y-6 md:gap-y-8">

            {/* Context */}
            <div className="space-y-4 col-span-4 md:col-span-7">
              <h2 className="text-lg uppercase font-bold font-sans-serif">Context</h2>
              <p className="text-md text-black/90 leading-[1.3] font-sans-serif font-light">
                The impact of climate change is becoming increasingly evident in large cities. According to records from the National Meteorological Service, last summer in Argentina was the warmest since systematic records began in 1961, experiencing 10 heatwaves, an unprecedented phenomenon for the country. The lack of urban planning and extreme weather events —such as increasingly stifling summers and persistent droughts in Argentina— translate into a phenomenon called "urban heat islands". These are areas where the temperature is higher than the surrounding environment. In Buenos Aires, there are several urban heat islands, usually generated by a combination of extensive concrete and little vegetation or water.
                <br /><br />
                In addition to discomfort, urban heat islands are critical because they impact public health and energy consumption, among other issues. Given this scenario, we combined journalistic research, data analysis, maps, and immersive visualizations to cover all aspects of the problem: what heat islands are and why they occur, their relationship with climate change, health effects, and the solutions adopted by other cities to mitigate this phenomenon.
              </p>
            </div>

            {/* 3-image grid */}
            <div className="col-span-4 md:col-span-8 grid grid-cols-3 md:grid-cols-8 gap-[15px] md:gap-[30px] my-[20px] md:my-[40px]">
              <div className="overflow-hidden col-span-1 md:col-span-2">
                <img src="/images/islas/buscador-3.png" alt="Detail" className="w-full h-auto object-cover" />
              </div>
              <div className="overflow-hidden col-span-1 md:col-span-2">
                <img src="/images/islas/buscador-1.png" alt="Detail" className="w-full h-auto object-cover" />
              </div>
              <div className="overflow-hidden col-span-1 md:col-span-2">
                <img src="/images/islas/buscador-2.png" alt="Detail" className="w-full h-auto object-cover" />
              </div>
            </div>

            {/* My role */}
            <div className="space-y-4 col-span-4 md:col-span-7">
              <h2 className="text-lg uppercase font-bold font-sans-serif">My role</h2>
              <p className="text-md text-black/90 leading-[1.3] font-sans-serif font-light">
                Firstly, with the backend and frontend development team we built an interactive map using data from the Urban Reporting based on Satellite Analysis (URSA) of the Inter-American Development Bank (IDB), with a street-level detail, allowing the audience to interact with the content and choose a specific point in the city, such as their home block or workplace street. This map visually presents the annual average ground temperature in different areas od the city compared to the average in rural areas. In some cases, differences of more than 20 degrees Celsius can be observed between different locations. This required the technical expertise of a data scientist and urbanist, who measured ground temperatures in 500 cities across Latin America and the Caribbean using Landsat 8 satellite images (NASA), with the Buenos Aires chapter presented in this production.
              </p>
            </div>

            <div className="overflow-hidden col-span-4 md:col-span-6">
              <img src="/images/islas/mapa.png" className="w-full h-auto object-cover" />
            </div>

            {/* Tools used */}
            <div className="space-y-4 col-span-4 md:col-span-7">
              <h2 className="text-lg uppercase font-bold font-sans-serif">Tools used</h2>
              <p className="text-md text-black/90 leading-[1.3] font-sans-serif font-light">
                To visualize the map, we used an in-house map server developed by La Nación, in combination with open-source JavaScript libraries such as Leaflet, Geoblaze, and Georaster. These libraries enabled us to integrate URSA data with our custom tile map. Additionally, we implemented the Nominatim API to power the street search feature, allowing user inputs to interact with the map.
              </p>
            </div>

            <div className="overflow-hidden col-span-4 md:col-span-7">
              <img src="/images/islas/mapa.png" className="w-full h-auto object-cover" />
            </div>

            {/* Video opening animation */}
            <div className="space-y-4 col-span-4 md:col-span-7">
              <h2 className="text-lg uppercase font-bold font-sans-serif">Video opening animation</h2>
              <p className="text-md text-black/90 leading-[1.3] font-sans-serif font-light">
                I also worked on implementing the animated project opening of videos, which featured animated bars as part of the visual interaction. For this, I used Svelte and D3 to build the height scales and the color transition. The videos were uploaded to JW Player, a video database, and I used the API to connect to the database and fetch the video. Additionally, I also used the Intersection Observer API to trigger the animation automatically when the video element enters the viewport as the user scrolls. We filmed the places with the highest and lowest ground temperatures for the animated opening project.
              </p>
            </div>

          </section>
        </main>

      </div>
    </div>
  );
}