'use client';
import Link from 'next/link';
import React, { PureComponent } from 'react';
import { Scrollama, Step } from 'react-scrollama';

export default class Demo extends PureComponent {
  state = {
    data: 1,
    steps: [
      {
        id: 1,
        title: 'CONTEXT',
        description: 'The impact of climate change is becoming increasingly evident in large cities. The lack of urban planning and extreme weather events translate into a phenomenon called "urban heat islands", which are areas where the temperature is higher than the surrounding environment. In Buenos Aires, there are several urban heat islands, usually generated by a combination of extensive concrete and little vegetation or water.',
        image: '/images/first-photo.png',
      },
      {
        id: 2,
        title: 'the project',
        description: 'Given this scenario, we combined journalistic research, data analysis, maps, and immersive visualizations to cover all aspects of the problem: what heat islands are and why they happen, their relationship with climate change, health effects, and the solutions adopted by other cities to mitigate this phenomenon.',
        image: '/images/second-photo.png',
      },
      {
        id: 3,
        title: 'PROCESS',
        description: 'Firstly, we partnered with a data scientist and urbanist to build an interactive map using data from the Urban Reporting based on Satellite Analysis (URSA) of the Inter-American Development Bank (IDB), with a street-level detail, allowing the audience to interact with the content and choose a specific point in the city, such as their home block or workplace street.',
        image: '/images/third-photo.png',
      },

      {
        id: 4,
        title: 'PROCESS',
        description: 'This map visually presents the annual average ground temperature in different areas od the city compared to the average in rural areas. In some cases, differences of more than 20 degrees Celsius can be observed between different locations.',
        image: '/images/third-photo.png',
      },
      {
        id: 5,
        title: 'PROCESS',
        description: 'We also did xxxxxx',
        image: '/images/third-photo.png',
      },
      {
        id: 6,
        title: 'my role',
        description: 'I developed To visualize the map, we used an in-house map server developed by La Nación, in combination with open-source JavaScript libraries such as Leaflet, Geoblaze, and Georaster. These libraries enabled us to integrate URSA data with our custom tile map. Additionally, we implemented the Nominatim API to power the street search feature, allowing user inputs to interact with the map.',
        image: '/images/third-photo.png',
      },
      {
        id: 7,
        title: 'my role',
        description: 'I also worked on implementing the animated project opening of videos, which featured animated bars as part of the visual interaction. For this, I used Svelte and D3 to build the height scales and the color transition. The videos were uploaded to a video database, and I used the API to connect to the database and fetch the video. Additionally, I also used the Intersection Observer API to trigger the animation automatically when the video element enters the viewport as the user scrolls. We filmed the places with the highest and lowest ground temperatures for the animated opening project.',
        image: '/images/third-photo.png',
      },
    ],
  };

  onStepEnter = ({ data }: { data: number }) => {
    this.setState({ data });
  };

  render() {
    const { data, steps } = this.state;
    const activeStep = steps.find((s) => s.id === data) || steps[0];

    return (
      <div className="relative">
        {/* Top Navbar */}
        <nav className="fixed top-0 left-0 z-20 flex p-4">
          <Link
            href="/"
            className="group flex items-center gap-2 font-sans text-xs font-light uppercase tracking-normal text-black no-underline hover:opacity-70 transition-all"
          >
            <span className="transition-transform group-hover:-translate-x-1">←</span>
            Back to Home
          </Link>
        </nav>

        {/* Hero Section */}
        <section className="pt-12 pb-16 px-[2vw] border-b border-black/10 h-[500px]">
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 lg:gap-12 items-start">

            {/* Left Column: Title & Publication (spans 5 cols) */}
            <div className="lg:col-span-5 space-y-2">
              <h1 className="text-2xl md:text-3xl leading-snug font-serif text-black/90">
                Urban Heat Islands. These Are the Hottest Places in Buenos Aires
              </h1>
              <p className="text-[14px] text-[#484848] uppercase tracking-wide">
                Published at La Nación
              </p>
            </div>

            {/* Right Column: Metadata Details in Sub-Columns (spans 7 cols) */}
            <div className="lg:col-span-7 grid grid-cols-2 sm:grid-cols-4 gap-6 items-start">
              <div>
                <h4 className="text-[12px] font-bold leading-[1.3] uppercase text-[#0063C5]">
                  Role
                </h4>
                <p className="text-sm font-light mt-1">Web Development</p>
              </div>

              <div>
                <h4 className="text-[12px] font-bold leading-[1.3] uppercase text-[#0063C5]">
                  Publication Date
                </h4>
                <p className="text-sm font-light mt-1">01/09/2022</p>
              </div>

              <div>
                <h4 className="text-[12px] font-bold leading-[1.3] uppercase text-[#0063C5]">
                  Co-Authors
                </h4>
                <p className="text-sm font-light mt-1">
                  La Nación's Visual, Data and Video Teams
                </p>
              </div>
            </div>

          </div>
        </section>

        {/* --- MOBILE VIEW: LINEAR STACK (No Scrollama, No Sticky) --- */}
        <section className="block md:hidden px-4 py-12 space-y-12">
          {steps.map((step) => (
            <article key={`mobile-${step.id}`} className="space-y-4">
              {step.title && (
                <h3 className="text-sm font-bold uppercase tracking-wider text-[#0063C5]">
                  {step.title}
                </h3>
              )}
              <p className="text-zinc-700 leading-relaxed text-base">
                {step.description}
              </p>
              <div className="w-full aspect-video bg-zinc-100 rounded-lg overflow-hidden border border-zinc-200">
                <img
                  src={step.image}
                  alt={step.title || 'Step Visual'}
                  className="w-full h-full object-cover"
                />
              </div>
            </article>
          ))}
        </section>

        {/* --- DESKTOP VIEW: SCROLLAMA CONTAINER --- */}
        <section className="hidden md:flex pt-[20vh] pb-[20vh] px-[2vw] justify-between gap-8">
          {/* Scrolling Steps Column */}
          <div className="basis-[35%]">
            <Scrollama onStepEnter={this.onStepEnter} offset={0.5}>
              {steps.map((step) => {
                const isVisible = step.id === data;
                return (
                  <Step data={step.id} key={`desktop-${step.id}`}>
                    <div className="min-h-screen flex items-center justify-center">
                      <div
                        className={`w-full p-8 bg-transparent`}
                      >
                        {step.title && (
                          <h3 className="text-sm font-sans-serif uppercase tracking-wider text-[#0063C5] mb-2">
                            {step.title}
                          </h3>
                        )}
                        <p className="font-sans-serif text-xl tracking-tight leading-tight">
                          {step.description}
                        </p>
                      </div>
                    </div>
                  </Step>
                );
              })}
            </Scrollama>
          </div>

          {/* Sticky Graphic Column */}
          <div className="basis-[60%] sticky top-[20vh] h-[60vh] w-full bg-zinc-100 border border-zinc-200 flex items-center justify-center rounded-xl overflow-hidden shadow-sm">
            <img
              src={activeStep.image}
              alt={activeStep.title || 'Section Image'}
              className="w-full h-full object-cover transition-opacity duration-300"
            />
          </div>




        </section>

        <div className="grid grid-cols-1 lg:grid-cols-20 gap-8 lg:gap-8 items-start">

          {/* Left Column: Title & Publication (spans 5 cols) */}
          <div className="lg:col-span-6 col-start-1">
            <p className="text-base font-sans-serif  tracking-tight">
              Firstly, we partnered with a data scientist and urbanist to build an interactive map using data from the Urban Reporting based on Satellite Analysis (URSA) of the Inter-American Development Bank (IDB), with a street-level detail, allowing the audience to interact with the content and choose a specific point in the city, such as their home block or workplace street.
              <br /><br />
              This map visually presents the annual average ground temperature in different areas od the city compared to the average in rural areas. In some cases, differences of more than 20 degrees Celsius can be observed between different locations.
            </p>
            
          </div>

           <div className="lg:col-span-6 col-start-6">
            
           
          </div>



        </div>
      </div>
    );
  }
}